"""
Generate robots.txt with configurable AI bot policies.

This module provides functionality to generate robots.txt files with
fine-grained control over different types of bots (training, search, traditional).
"""

from typing import List, Optional


class RobotsConfig:
    """Configuration for robots.txt generation."""

    def __init__(
        self,
        block_ai_training: bool = True,
        allow_ai_search: bool = True,
        allow_traditional: bool = True,
        crawl_delay: Optional[int] = None,
        custom_rules: Optional[List[str]] = None,
        disallowed_paths: Optional[List[str]] = None,
        block_ai_training_docs: bool = False,
    ):
        """
        Initialize robots.txt configuration.

        Args:
            block_ai_training: Block AI training data collection bots
            allow_ai_search: Allow AI search and citation bots
            allow_traditional: Allow traditional search engine bots
            crawl_delay: Crawl delay in seconds (rate limiting)
            custom_rules: Additional custom rules to include
            disallowed_paths: Paths to disallow for all bots
            block_ai_training_docs: Extend `block_ai_training` to the corpus
                routes themselves (`/llms.txt`, `/llms-small.txt`,
                `/llms-full.txt`, and the per-page `/<page>/llms.txt`).
                Defaults to False, which is the historical behaviour: those
                documents exist to be read by machines, so blocking a
                training bot from the app's PAGES while still serving it the
                corpus is the deliberate default. Set True when the corpus
                itself is the thing you are protecting. `/robots.txt` and
                `/sitemap.xml` are never gated: robots.txt is where the
                block is announced, and a bot that receives 403 for it
                treats the site as having no rules at all (RFC 9309) — the
                opposite of what blocking is for.
        """
        self.block_ai_training = block_ai_training
        self.allow_ai_search = allow_ai_search
        self.allow_traditional = allow_traditional
        self.crawl_delay = crawl_delay
        self.custom_rules = custom_rules or []
        self.disallowed_paths = disallowed_paths or []
        self.block_ai_training_docs = block_ai_training_docs


def _vendor_groups(cls: str, directive: str) -> list:
    """User-agent groups for every registry vendor of one class.

    One group per robots token, in registry order — which deliberately
    keeps the pre-2.7.0 vendors first so existing hosts' robots.txt keeps
    its familiar shape with 2.7.0's additions appended, never interleaved.
    A vendor with no robots tokens (anthropic-legacy) emits nothing; that
    absence is a hard-won rule and is regression-tested.
    """
    from .vendors import vendors_of_class

    lines = []
    for vendor in vendors_of_class(cls):
        for token in vendor.robots_tokens:
            lines.extend([f"User-agent: {token}", f"{directive}: /", ""])
    return lines


def generate_robots_txt(config: RobotsConfig, sitemap_url: str, base_url: str) -> str:
    """
    Generate robots.txt content based on configuration.

    Args:
        config: Robots.txt configuration
        sitemap_url: Full URL to sitemap.xml
        base_url: Base URL of the application

    Returns:
        Complete robots.txt content
    """

    lines = [
        "# Robots.txt for Dash Application",
        "# Generated by dash-improve-my-llms",
        "# https://pypi.org/project/dash-improve-my-llms/",
        "",
        "# Default policy - allow all standard crawlers",
        "User-agent: *",
        "Allow: /",
    ]

    # Disallowed paths and crawl delay belong INSIDE the `User-agent: *`
    # group — through 2.6.x they were emitted after the blank line that
    # closes it, leaving them orphaned from any group in strict RFC 9309
    # parsers (defect P5). The group now closes after its last directive.
    if config.disallowed_paths:
        for path in config.disallowed_paths:
            lines.append(f"Disallow: {path}")

    if config.crawl_delay:
        lines.append(f"Crawl-delay: {config.crawl_delay}")

    lines.append("")

    # Block AI training bots if configured. Groups render from the vendor
    # registry (vendors.py) — the SAME source get_bot_type() classifies
    # from, so what this file says and what the middleware does cannot
    # drift (the construction that killed defects P1/P2/P3). The legacy
    # aliases (anthropic-ai, Claude-Web) are deliberately NOT emitted:
    # claude.ai's user-initiated fetcher honours a disallow on them, so
    # blocking the deprecated names blocks the paste-into-Claude audience
    # while blocking no training — their registry record has no robots
    # tokens.
    if config.block_ai_training:
        lines.extend(
            [
                "# ==========================================",
                "# Block AI Training Data Collection",
                "# ==========================================",
                "# These bots collect data to train AI models.",
                "# Blocking them prevents your content from being",
                "# used in training datasets without permission.",
                "",
            ]
        )
        lines.extend(_vendor_groups("training", "Disallow"))

    # Allow AI search/citation bots if configured
    if config.allow_ai_search:
        lines.extend(
            [
                "# ==========================================",
                "# Allow AI Search and Citation Bots",
                "# ==========================================",
                "# These bots help users find your content through",
                "# AI-powered search engines and assistants.",
                "",
            ]
        )
        # Claude-User fetches when a person asks Claude to read a URL;
        # Claude-SearchBot indexes for citation. The named-human fetchers
        # are the audience llms.txt exists for — never in the training
        # block. Groups render from the registry's search class.
        lines.extend(_vendor_groups("search", "Allow"))

    # Traditional search bots. With the default True the block stays
    # comments-only — the engines ride `User-agent: *` exactly as they
    # always have. With False the registry's traditional vendors get real
    # Disallow groups: through 2.6.x the knob only deleted a comment and
    # did nothing (defect P4).
    if config.allow_traditional:
        lines.extend(
            [
                "# ==========================================",
                "# Traditional Search Engines",
                "# ==========================================",
                "# Standard search engine bots are allowed",
                "# by default with the User-agent: * rule above.",
                "",
                "# Googlebot, Bingbot, etc. - covered by *",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "# ==========================================",
                "# Traditional Search Engines — blocked",
                "# ==========================================",
                "",
            ]
        )
        lines.extend(_vendor_groups("traditional", "Disallow"))

    # Add custom rules
    if config.custom_rules:
        lines.extend(
            [
                "# ==========================================",
                "# Custom Rules",
                "# ==========================================",
                "",
                *config.custom_rules,
                "",
            ]
        )

    # Always include sitemap reference
    lines.extend(
        [
            "# ==========================================",
            "# Sitemaps and Discovery",
            "# ==========================================",
            f"Sitemap: {sitemap_url}",
            "",
        ]
    )

    # Add helpful links for AI agents
    lines.extend(
        [
            "# ==========================================",
            "# AI-Friendly Documentation",
            "# ==========================================",
            "# For AI agents and LLMs, we provide structured",
            "# documentation in multiple formats:",
            "#",
            f"# {base_url}/llms.txt - LLM-friendly prose documentation",
            f"# {base_url}/sitemap.xml - Complete sitemap",
            "#",
            "# MCP-aware clients can also fetch per-page docs as",
            "# resources via Dash 4.3+ MCP server endpoints.",
            "",
        ]
    )

    return "\n".join(lines)
